# Formulare und RSForm!Pro 
In diesem Kapitel beschäftigen wir uns ausführlich damit, wie Anmeldungen und andere Formulare mit RSForms!Pro erstellt und verwaltet werden können. 

> RSForms findest du unter Komponenten/RSForm! Pro

## Konkret: Anmeldeformular erstellen

Mithilfe von RSForms kannst du ganz einfach ein Anmeldeformular erstellen. Nutze dafür bitte eine der Vorlagen, damit die Verknüpfungen im Backend richtig gesetzt und alle rechtlichen Hinweise vorhanden sind! Dir stehen die folgenden Vorlagen zur Verfügung:

* Vorlage (Standard / normal / ausführlich / Groß), Formularname: vorlage-anmeldung-designed
* Vorlage kurz (nur das Nötigste), Formularname: vorlage-anmeldung-kurz

Anhand der Standard-Vorlage wird im folgenden erklärt, wie du das Anmeldformular nun anpassen kannst. Mindestens ein kopieren ist unbedingt erforderlich.

### Standard-Vorlage an die eigenen Bedürfnisse anpassen

1. Du kopierst das Formular, indem du es auswählst und oben Kopieren klickst.
2. Du öffnest das Formular
3. Im Tab Eigenschaften änderst du unter dem Menüpunkt "Formular Eigenschaften" Titel und Namen des Formulars.  
   Der Formulartitel wird am Ende über deinem Formular angezeigt werden. Möchtest du das nicht, kannst du es hier ausstellen (unter "Formulartitel anzeigen; Nein / Ja").  
   Der Formularname ist wie ein Variablenname und wird nicht auf der Website angezeigt. Die Benennung folgt der Konvention: anmeldung-xxx-yyyy, wobei xxx für den Veranstaltungsnamen und yyyy für das Veranstaltungsjahr steht. Verwende bitte nur kleinbuchstaben und keine Sonderzeichen oder Umlaute! Im Falle von Veranstaltungen, für die Abkürzungen gebräuchlich sind (z.B. LV), kannst du auch gerne die Abkürzung verwenden. Beispiele für Formularnamen sind: anmeldung-grenzgaengerin-2022, anmeldung-lv-ii-2022.
4. Wechsle zurück zum Tab Komponenten.  
   An der Seite siehst du die verschiedenen Felder, die du einfügen kannst (Hinweis: Verwende auf keinen Fall Google Maps - das widerspricht unserem Umgang mit Daten!). Die allermeisten Felder sollten bereits vorhanden sein. Wenn du Felder nicht benötigst, kannst du sie getrost löschen (Stichwort: Datensparsamkeit!)

#### E-Mail an die Veranstaltungsleitung gewünscht?

Wenn du eine E-Mail bekommen möchtest, wenn jemand das Formular absendet, kannst du das im Tab Eigenschaften unter dem Menüpunkt "E-Mail an Admin" einstellen. Füge noch eine E-Mail-Adresse für den\*die Empfänger\*in (Recipient) hinzu, und schon bekommt die entsprechende E-Mail eine Benachrichtigung bei erfolgreicher Anmeldung.

### Formular einbinden

#### Anmeldeformular

Ein Anmeldeformular bindest du über den Code

```
{rsform Formular-ID}
```

also zum Beispiel: {rsform 6}

#### Abmeldeformular

Rechtlich sind wir auch dazu verpflichtet, ein Formular zur Abmeldung zu erstellen. Dieses kannst du mit `{loadposition form-abmeldung-designed}` einbinden. Damit wird ein ausklappbarer Kasten eingebunden, der das Formular zur Abmeldung beinhaltet.

> Das Abmeldeformular tut im Grunde nichts anderes, als das Labü via E-Mail darüber zu informieren, dass sich eine Person von einer Veranstaltung abmelden möchte.

## 3\. Weiterführendes und Spezielleres

Detailreichere Erklärungen zu den Funktionen von RSForms folgen nun unter 2. Spezielleres. Dort findest du auch Hinweise zum Erstellen Bedingter Felder.

Für Nerds: Die Verknüpfung mit der Datenbank von sketch.dates funktioniert über das Einfügen des Codeschnipsels

```
Joomla\Component\SketchDates\Administrator\Helper\SketchDatesRsconnect::connectRs($adminEmail);
```

in dem Feld "Das Script wird aufgerufen, bevor die E-Mail an den Admin gesendet wird." unter PHP E-Mail-Skripte in den Eigenschaften des Formulars.

### Tab Komponenten:

in Klammern jeweils optional vorhanden (durch eine bestimmte Auswahl)

#### Formular-Tab: Allgemein

| Option | kommt vor bei.... | Erklärung |
|--------|-------------------|-----------|
| Name | Textbox, Textbereich, Dropdown, Checkbox-Gruppe, Radio-Gruppe, Senden, Passwort, Datei hochladen, Freier Text, Kalender, Date and Time Picker, Schaltfläche, CAPTCHA Sicherheitscode, Verstecktes Feld, Registrierungscode, Seitenumbruch, Geburtstags-Feld, Range Slider | Das ist der Variablenname eines Formular-Feldes. Er ist v.a. aus technischer Sicht wichtig. |
| Beschriftung | Textbox, Textbereich, Dropdown, Checkbox-Gruppe, Radio-Gruppe, Senden, Beschriftung, Datei hochladen, Kalender, Date and Time Picker, Schaltfläche, CAPTCHA Sicherheitscode, Geburtstags-Feld, Range Slider | Was hier eingetragen wird, erscheint über dem Formular-Feld. |
| Standardwert | Textbox, Textbereich, Passwort, Kalender, Date and Time Picker, Verstecktes Feld, Range Slider | Was hier eingetragen wird, wird als Text ins Formular-Feld eingefügt - der Wert des Feldes wird also standardmäßig festgelegt. Dieses Feld ist nicht so relevant für uns. |
| Beschreibung | Textbox, Textbereich, Dropdown, Checkbox-Gruppe, Radio-Gruppe, Passwort, Datei hochladen, Kalender, Date and Time Picker, Schaltfläche, CAPTCHA Sicherheitscode, Geburtstags-Feld, Range Slider | Was hier eingetragen wird, erscheint unter dem Formular-Feld und dient näheren Beschreibungen des einzutragenen Inhalts. Bsp.: Handynummer |
| Veröffentlicht | Textbox, Textbereich, Dropdown, Checkbox-Gruppe, Radio-Gruppe, Senden, Passwort, Datei hochladen, Freier Text, Kalender, Date and Time Picker, Schaltfläche, CAPTCHA Sicherheitscode, Verstecktes Feld, Registrierungscode, Seitenumbruch, Geburtstags-Feld, Range Slider | Ist relativ selbsterklärend. Soll das Formular-Feld verwendet werden, muss ja angekreuzt sein. |
| Einträge | Dropdown, Checkbox-Gruppe, Radio-Gruppe | Die optimale Eingabe ist (Bild einfügen: Screenshot-Dropdown bzw. Checkbox bzw. Radio-Eintraege). Die Zeichenfolge vor dem Queerstrich ist der Name der Optionsvariable (Bsp.: MDE). Mit ihm kann beispielsweise durch bedingte Felder weitergearbeitet werden. Die Zeichenfolge nach dem Queerstrich ist das, was dem\*der Benutzer\*in angezeigt wird, wenn er\*sie das Dropdown-Menü ausklappt. Bei der ersten Option steht keine Zeichenkette vorm Queerstrich. Das bedeutet, dass die Option ausschließlich angezeigt wird (und nicht ausgewählt werden kann) und sichtbar ist, wenn das Dropdown-Menü nicht ausgeklappt ist. |
| Label | Senden, Schaltfläche | Das Label ist die Aufschrift des Buttons. |

#### Formular-Felder: Tab Validierungen

| Option | kommt vor bei... | Erklärung |
|--------|------------------|-----------|
| Erforderlich | Textbox, Textbereich, Dropdown, Checkbox-Gruppe, Radio-Gruppe, Passwort, Datei hochladen, Kalender, Date and Time Picker, Geburtstags-Feld, Range Slider | selbsterklärend |
| Validierungsregel | Textbox, Textbereich, Passwort | Wenn nur Zahlen in das Feld eingetragen werden sollen, kann das über diese Option konfiguriert werden. Achtung: Telefonnummern haben hier kein deutsches Format und sollten deswegen nicht über die Konfiguration Telefonnummer validiert werden. Bei PLZs solltest du bedenken, dass diese mit 0 beginnen können, numerische Werte jedoch nicht mit null beginnen können. |
| Validierungsnachricht | Textbox, Textbereich, (Dropdown), (Checkbox-Gruppe), (Radio-Gruppe), Passwort, Datei hochladen, Kalender, Date and Time Picker, CAPTCHA Sicherheitscode, Geburtstags-Feld, (Range Slider) | Hier kannst du die Nachricht eintragen, die der\*die Benutzer\*in bekommen soll, wenn das Feld fehlerhaft ausgefüllt wurde |
| Datum korrigieren | Kalender, Date and Time Picker | Zur Verbindung von zwei Kalendern im selben Formular. |
| Date validation | Kalender, Date and Time Picker | Bei Ja wird das Datum anhand des korrekten Datumformats validiert. |
| Fehlerhaftes Datum zulassen (z.B. 31. Februar 2013) | Geburtstags-Feld | Wenn ja, werden fehlerhafte Daten (die nicht existieren) nicht akzeptiert. |
| Validierungsregel | Geburtstags-Feld | Auswahlmöglichkeiten: Keine Validierung, Ab heute (inklusive heute), Ab morgen, Bis heute (exklusive heute), Bis heute (inklusive heute) |

#### Formular-Felder: Tab Attributes

| Option | kommt vor bei... | Erklärung |
|--------|------------------|-----------|
| Type | Textbox | Das ist der Typ, unter dem die Eingabe abgespeichert wird. |
| Größe | Textbox, Dropdown, Passwort, CAPTCHA Sicherheitscode | Das ist die Länge des Feldes. Wenn also viel Eingabe zu erwarten ist, sollte hier eine größere Zahl eingetragen werden, als bei z.B. einer Hausnummer. Die Zahl bezieht sich auf die Zeichenzahl und ist nicht verbindlich, sondern bestimmt lediglich die Darstellungsgröße des Feldes. |
| Maximalgröße | Textbox, (Textbereich), Passwort | Das ist die maximale Zeichenzahl, die der\*die Benutzer\*in eingeben kann. |
| Placeholder | Textbox, Textbereich, Passwort | Was hier eingetragen wird, erscheint leicht ausgegraut im Formularfeld und verschwindet, sobald der\*die Benutzer\*in eine Eingabe tätigt. |
| Zusätzliche Attribute | Textbox, Textbereich, Dropdown, Checkbox-Gruppe, Radio-Gruppe, Senden, Passwort, Datei hochladen, Kalender, Date and Time Picker, Schaltfläche, CAPTCHA Sicherheitscode, Verstecktes Feld, Registrierungscode, Seitenumbruch, Geburtstags-Feld | Hier können mithilfe von CSS neue, über die existierenden Attribute hinausgehende Attribute erstellt werden. Ist aber eher was für Nerds. |
| Spalten | Textbereich | Bestimmt zusammen mit Zeilen die Größe des Textfeldes. |
| Zeilen | Textbereich | Bestimmt zusammen mit Spalten die Größe des Textfeldes. |
| WYSIWYG Editor verwenden | Textbereich | Hier muss Nein ausgewählt werden |
| Show Charakter Count | Textbereich | Ist diese Option aktiviert, werden dem\*der Benutzer\*in die "aktuelle" Zeichenzahl angezeigt. Bsp.: 37/120 |
| Multiple | Dropdown, Datei hochladen | Bei Ja sind mehrere Antworten (bzw. Dateien) möglich, bei Nein nur eine einzige. |
| Anordnung | Checkbox-Gruppe, Radio-Gruppe, CAPTCHA Sicherheitscode | Hier kann die Anordnung der Checkboxen/Radio-Buttons ausgewählt werden. Je nach Länge und Anzahl ergeben die Optionen Horizontal, Vertikal und Vertikal in 2, 3, 4 oder 6 Reihen mehr oder weniger Sinn. |
| Maximal Selections | Checkbox-Gruppe | Hier kann die maximale Anzahl der Benutzer\*innenauswahl angegeben werden. Wenn der\*die Nutzer\*in also nur 3 Sachen der Checkbox-Gruppe auswählen soll, solltest du 3 hier eintragen. |
| Minimal Selections | Checkbox-Gruppe | Genauso wie bei Maximal Selections, nur mit minimaler Anzahl ;) |
| Reset | Senden, Schaltfläche | Wenn ja ausgewählt ist, wird zusätzlich auch ein Reset (Zurücksetzen)-Button eingefügt. |
| Label für Reset | Senden | Das ist die Aufschrift des Reset-Buttons. |
| Label für Zurück | Senden | Das ist die Aufschrift des Zurück-Buttons. Der Zurück-Button wird bei mehreren Formular-Seiten relevant. |
| Fortschrittsanzeige | Senden, Seitenumbruch | Bei Aktivierung wird eine Fortschrittsanzeige (basierend auf dem Fortschritt nach Seitenzahlen des Formulars) generiert. Diese kann entweder automatisch generiert oder selbst in CSS geschrieben werden. Für uns ist die Option nicht so relevant. |
| Schaltflächentyp | Senden, Schaltfläche, Seitenumbruch | Hier muss <button> ausgewählt werden. |
| Dateigröße | Datei hochladen | Hier kann die maximal hochladbare Dateigröße in kB eingestellt werden (Achtung, binäres Format beachten: 1024kB = 1 MB) |
| Ziel | Datei hochladen | Upload-Ordner festlegen (siehe dazu: Ordnerstruktur Website) |
| Allow only images | Datei hochladen | Hier kann festgelegt werden, ob nur Bilder hochgeladen werden dürfen |
| Erlaubte Erweiterungen (jeweils in einer neuen Zeile) | Datei hochladen | Hier kann ein bestimmtes Dateiformat (z.B. pdf) festgelegt werden, das hochgeladen werden darf. Mehrere sind ebenfalls möglich, allerdings müssen sie jeweils in einer neuen Zeile geschrieben werden. |
| Sanitize Filename | Datei hochladen | Keine Ahnung, was das macht. |
| Datei-Präfix (leer lassen für Standard) | Datei hochladen | Hiermit kann der Datei-Präfix bearbeitet werden. Ist eher was für "Nerds". |
| Datei anhängen an | Datei hochladen | Hiermit kann die hochgeladene Datei als Anhang per E-Mail verschickt werden (dazu müssen unbedingt die E-Mail-Einstellungen entsprechend konfiguriert sein!). Die Auswahl erfolgt, in dem du die Strg-Taste gedrückt hältst und dann per Mausklick auswählst. |
| Datumsformat | Kalender, Date and Time Picker | Hier kann das Datumsformat festgelegt werden. Es empfiehlt sich natürlich, das Standardformat im Deutschen zu benutzen: [dd.mm](http://dd.mm).yyyy. Beim Date and Time Picker muss die Uhrzeit noch beachtet werden. |
| Kalender Layout | Kalender, Date and Time Picker | Flat oder Popup. Flat bedeutet, der Kalender ist schon ausgeklappt, bei Popup muss er von dem\*der Benutzer\*in mit einem Button ausgeklappt werden. |
| Min. Datum (mm/dd/yyyy) | Kalender | Hier kann ein Datum angegeben werden. Der\*die Benutzer\*in kann kein Datum auswählen, das vor dem hier angegebenen ist. Format: mm/dd/yyyy |
| Max. Datum (mm/dd/yyyyy) | Kalender | Wie das Min. Datum nur andersrum. |
| Popup Label | (Kalender) | Die Beschriftung des Buttons, mit dem der Kalender ausgeklappt werden kann. |
| Nur lesen | (Kalender), Range Slider | Bei ja hat der\*die Benutzer\*in ausschließlich Lese- und keinen Schreibzugriff. |
| Min Date (m/d/Y H:i) | Date and Time Picker | Der\*die Benutzer kann kein Datum auswählen, das vor dem hier angegebenen liegt. Datumsformat: m/d/Y H:i |
| Max Date (m/d/Y H:i) | Date and Time Picker | Wie Min Date nur andersherum. |
| Allowed Dates Regex (m/d/Y) | Date and Time Picker | Der Kalender zeigt nur die Daten, die hier spezifiziert sind. Bspw. würde der Code \\d{2}/25/\\d{4} würde jeden 25. Tag jeden Monats in jedem Jahr anzeigen. |
| Allowed Dates (m/d/Y) | Date and Time Picker | Im Grunde wie auch Allowed Dates Regex |
| Display Time Picker | Date and Time Picker | Bei ja wird neben dem Kalender auch die Zeitauswahl gezeigt. |
| Timepicker format (eg. H:i) | (Date and Time Picker) | Hier kann das Zeitformat festgelegt werden. |
| Minute Step (eg. 10) | (Date and Time Picker) | Hier wird festgelegt, wie der Abstand der Minutenauswahl ist. |
| Min Time (H:i) | (Date and Time Picker) | Analog zu Min Date |
| Max Time (H:i) | (Date and Time Picker) | Analog zu Max Date |
| Schema/Template | Date and Time Picker | Auswahl: light/dark (selbsterklärend) |
| Bild-Erzeugung | CAPTCHA Sicherheitscode | Auswahl: Grafiken verwenden, Schrift verwenden, Unsichtbar. Wir empfehlen, Grafiken zu verwenden. |
| Länge | CAPTCHA Sicherheitscode, Registrierungscode | Länge des Sicherheits-/Registrierungscodes |
| Hintergrundfarbe | CAPTCHA Sicherheitscode | Hintergrundfarbe als HEX-Wert |
| Typ | CAPTCHA Sicherheitscode | Zeichentyp, der im CAPTCHA verwendet wird: Zahlen, Buchstaben oder alphanumerisch |
| Aktualisierung zeigen | CAPTCHA Sicherheitscode | Ist hier ja ausgewählt, wird ein Button neben dem CAPTCHA dargestellt, mithilfe dessen das CAPTCHA neu generiert werden kann. Userfriendlier, also gerne mit ja markieren. |
| Text für Aktualisieren | (CAPTCHA Sicherheitscode) | Wird auf den Text geklickt, generiert RSForms ein neues CAPTCHA |
| Type | Registrierungscode | Entweder random oder sequential. Random bedeutet zufällig auf Grundlage der zu definierenden Zeicheneinstellungen. Sequential bedeutet eine fortlaufende Reihenfolge |
| Zeichen | (Registrierungscode) | Zeichentyp, der im Registrierungscode verwendet wird: Zahlen, Buchstaben oder alphanumerisch |
| Label für Weiter | Seitenumbruch | Beschriftung des Weiter-Buttons |
| Label für Zurück | Seitenumbruch | Beschriftung des Zurück-Buttons |
| Validieren beim Ändern der Seite | Seitenumbruch | Wenn ja, werden beim Ändern der Seite die Validierungen überprüft. |
| Feldsortierung | Geburtstags-Feld | Sortierung der verschiedenen Felder für Tag, Monat und Jahr. Zu empfehlen ist: Tag, Monat, Jahr |
| Datumstrennzeichen | Geburtstags-Feld | Das Feld kann frei gelassen werden. |
| Tagesauswahl anzeigen | Geburtstags-Feld | Wenn ja ausgewählt ist, darf der\*die Benutzer\*in auch den Tag auswählen. |
| Anzeige von 'Bitte Datum wählen' an Tagesauswahl - leer lassen, um Anzeige zu unterbinden | Geburtstags-Feld | Beschriftung der Tages-Dropdown-Auswahl (Empfehlung: Tag) |
| Tagesanzeige | Geburtstags-Feld | Tag mit oder ohne führende Null anzeigen (01. oder 1.) |
| Monatsauswahl anzeigen | Geburtstags-Feld | Wenn ja ausgewählt ist, darf der\*die Benutzer\*in auch den Monat auswählen. |
| Anzeige von 'Bitte Datum wählen' an Monatsauswahl - leer lassen, um Anzeige zu unterbinden | Geburtstags-Feld | Beschriftung der Monats-Dropdown-Auswahl (Empfehlung: Monat) |
| Monatsanzeige | Geburtstags-Feld | Monat mit oder ohne führende Null anzeigen (01. oder 1.) oder in Kurzform (Jan) oder Langform (Januar) |
| Jahresauswahl anzeigen | Geburtstags-Feld | Wenn ja ausgewählt ist, darf der\*die Benutzer\*in auch das Jahr auswählen. |
| Anzeige von 'Bitte Datum wählen' an Jahresauswahl - leer lassen, um Anzeige zu unterbinden | Geburtstags-Feld | Beschriftung der Jahres-Dropdown-Auswahl (Empfehlung: Jahr) |
| Start | Geburtstags-Feld | Start-Jahr |
| Ende | Geburtstags-Feld | End-Jahr |
| Führende Null in Tag/Monat speichern? | Geburtstags-Feld | Wenn ja ausgewählt ist, wird die führende Null beim Tag oder Monat nicht nur angezeigt, sondern auch gespeichert. |
| Slider Type | Range Slider | Single oder Double. Bei Single gibt es einen Marker, bei Double zwei, um die beiden Außengrenzen des Ranges zu markieren. |
| Skin | Range Slider | Flat, HTML 5, Modern, Nice, Simple - Auswahl des Darstellungstyps |
| Use Values | Range Slider | Hiermit können nochmal spezifische Wertgrenzen für den Slider eingesetzt werden (anstatt eines Mini- und Maximums) |
| Values | (Range Sliders) | Hier werden die Werte eingetragen, falls Values aktiviert wurde. Für jeden Wert eine neue Zeile. |
| Show Grid | Range Sliders | Zeigt eine Skala/Gitter unterhalb des Sliders. |
| Force Edges | Range Sliders | ? |
| Allow Keyboard Controls | Range Sliders | Erlaubt dem\*der Benutzer\*in die Nutzung der Tastatur (Pfeil links/rechts) zur Bedienung des Sliders. |

* Das Feld "Freier Text" hat zusätzlich den Tab "HTML". Dort ist ausschließlich der aus den Blogbeiträgen bekannte Editor zu finden.
* Im Zusätzlichen Attribut des Geburtstags-Feldes sollte für die automatische Berechnung des Alters folgender Code stehen: onchange="calculateAge();"

Bilder von den verschiedenen Feldern einfügen. Wie sieht es im Frontend aus?

#### Die verschiedenen Felder und ihre Nutzung

##### Textbox

Textboxen sind für die meisten Felder ausreichend. Nutzungsbsp.: Name  
[Bild einfügen]

##### Textbereich

Textbereiche sind nützlich, wenn etwas mehr Text abgefragt wird. Also bspw. beim Hinweise-Feld  
[Bild einfügen]

##### Dropdown

Dropdowns sind nützlich, wenn es eine feste Auswahl gibt, bei der es in der Regel nur eine Auswahloption gibt. Dropdowns können quasi analog zu Radio-Buttons verwendet werden. Bsp.: VCP-Länder-Auswahl  
[Bild einfügen]

##### Checkbox-Gruppe

Eine Checkbox-Gruppe ist sinnvoll, wenn es mehrere Antwortmöglichkeiten bei der Auswahl gibt. Bsp.: Mengenabfrage Kaffee, Müsli  
[Bild einfügen]

##### Radio-Gruppe

Analog zu Dropdown. Bsp.: Essensauswahl  
[Bild einfügen]

##### Senden

Unabdingbarer Bestandteil des Formulars.  
[Bild einfügen]

##### Passwort

Ist dann nützlich, wenn aus irgendeinem Grund ein Passwort von dem\*der Benutzer\*in festgelegt werden soll, das weiterverarbeitet wird.  
[Bild einfügen]

##### Datei hochladen

Dateien hochzuladen kann bspw. bei der Foto- und Filmvereinbarung nützlich sein.  
[Bild einfügen]

##### Freier Text

Freier Text kann genutzt werden, um Informationstext ins Formular einzubauen - z.B. die Überschrift.  
[Bild einfügen]

##### Date and Time Picker

[Bild einfügen]

##### Schaltfläche

Mit der Schaltfläche könnte bspw. ein bestimmter Code in Gang gesetzt werden. Kann unter Umständen nützlich sein.  
[Bild einfügen]

##### CAPTCHA Sicherheitscode

Ein CAPTCHA sollte **immer** am Ende des Formulars abgefragt werden, um Spam zu verhindern.  
Wir nutzen folgende Einstellungen:

* Bild-Erzeugung: Grafiken verwenden
* Länge: 5
* Hintergrundfarbe: #FFFFFF (weiß)
* Textfarbe: #000000 (schwarz)
* Typ: Zahlen
* Anordnung: Vertikal
* Aktualisierung zeigen: Ja
* Text für Aktualisieren: Neues Captcha generieren
* Größe: 30

[Bild einfügen]

##### Verstecktes Feld

Versteckte Felder (Hidden Fields) sind nützlich für die Arbeit mit bedingten Feldern (siehe Tab Eigenschaften).  
[Bild einfügen]

##### Registrierungscode

Der Registrierungscode generiert eine Anmelde-ID für den\*die Benutzer\*in. Das benötigen wir in der Regel nicht.  
[Bild einfügen]

##### Seitenumbruch

Seitenumbrüche sind sehr nützlich, wenn das Formular sehr lang ist.  
[Bild einfügen]

##### Geburtstags-Feld

Mit dem Geburtstags-Feld können Geburtstage gut und einfach abgefragt werden.  
[Bild einfügen]

##### Range Slider

Der Range Slider ist nützlich, um bspw. eine Meinung oder eine Tendenz mehr oder weniger attraktiver abzufragen.  
[Bild einfügen]

### Tab Eigenschaften

#### Formular Layout

Hier sollte nichts verändert werden!

Unsere Einstellungen sind wie folgt:

* Responsive Layouts: Responsive (CSS3)
* Load Layout CSS / JS: Ja
* Layout Flow: Vertical (label on top field)
* Layout automatisch erstellen: Ja
* HTML Layout:

```
<!-- ganz viel HTML-Text, der kopiert, aber nicht bearbeitet werden kann -->
```

#### CSS und Javascript

Hier kann mit CSS bzw. Javascript gearbeitet werden. Möglich ist darüber z.B. die automatische Berechnung des Alters bei Veranstaltungsbeginns. Dieser Bereich sollte nur bearbeitet werden, wenn du dich mit CSS und / oder Javascript auskennst! (Definition von auskennen: Du weißt, was du tust und kannst es auch wieder rückgängig machen)

* CSS

```
<style type="text/css">
.anmeldung input[type="text"], .anmeldung input[type="url"], .anmeldung input[type="email"], .anmeldung input[type="password"], .anmeldung input[type="number"] {
  background-color: hsla(0.5,0%,100%,.7) !important;
  padding: 12px !important;
  outline: none;
  border-radius: 0 !important;
  width: 100% !important;
  box-sizing: border-box !important;
  height: auto !important;
}
.formResponsive textarea{
  width: 100%;
  height: 5rem;
  padding: 12px;
  outline: none;
  border-radius: 0 !important;
  box-sizing: border-box;
  background-color: hsla(0.5,0%,100%,.7) !important;
}
.formResponsive .rsform-submit-button{
  background: #004287 !important; 
  color: #fff;
  padding: 16px 20px !important;
  display: inline-block !important;
  position: relative !important;
  transition: all .3s ease 0s !important;
  box-shadow: 0 3px 6px #00000029 !important;
  outline: 0 !important;
  border: 0 !important;
  border-radius: 0 !important;
  text-shadow: none !important;
  float: left;
  font-size: 16px !important;
  font-size: 1rem !important;
  font-weight: bold;
  line-height: 1.6;
}
.formResponsive .rsform-reset-button{
  background: #e94653!important;
  color: #fff;
  padding: 16px 20px !important;
  margin-left: 55px;
  display: inline-block !important;
  position: relative !important;
  transition: all .3s ease 0s !important;
  box-shadow: 0 3px 6px #00000029 !important;
  outline: 0 !important;
  border: 0 !important;
  border-radius: 0 !important;
  text-shadow: none !important;
  float: left;
  font-size: 16px !important;
  font-size: 1rem !important;
  font-weight: bold;
}
</style>
```

* Javascript

```
<script type="text/javascript">
function calculateAge(){
  let textEntry = document.getElementsByClassName('sketchdates-datetime')[0].nextElementSibling.innerHTML;
  let startDate = new Date(textEntry.substr(6,4), textEntry.substr(3,2) - 1, textEntry.substr(0,2));
	let year= parseInt(document.getElementById('Geburtstagy').value,10);
	let month = parseInt(document.getElementById('Geburtstagm').value,10)-1;
	let day = parseInt(document.getElementById('Geburtstagd').value,10);
	let age = startDate.getFullYear() - year;
	if (month > startDate.getMonth()) {
    age = age - 1;
	};
	if (month === startDate.getMonth()) {
    if (day > startDate.getDate()) {
		  age = age - 1;
    };
  };
  if (!isNaN(age)) {
    document.getElementById('AlterBeiVeranstaltungsbeginnAnzeige').innerText= "Alter bei Veranstaltungsbeginn: " +(age); 
    document.getElementById('AlterBeiVeranstaltungsbeginn').value= age.toString(); 
  };
};
window.onload = function(){
  let deadline = document.getElementById('deadline').value;
  let deadlineDate = new Date(deadline.substr(6,4), deadline.substr(3,2)-1 , deadline.substr(0,2), deadline.substr(11,2), deadline.substr(14,2), deadline.substr(17,2));
  let today = new Date(); 
  if (today > deadlineDate){
    document.getElementById('userForm').innerHTML = "<p>Die Anmeldefrist ist bereits abgelaufen.</p>";
  };
};
</script>
```

#### Formular Eigenschaften

Hier müssen einige wichtige Einstellungen vorgenommen werden. Die Dinge, die du verändern oder festlegen wolltest, sind **fett** markiert.

* Veröffentlicht: Ja
* Zugriffsebene: Alle
* **Formulartitel**: Der Formulartitel wird am Ende über deinem Formular angezeigt werden.
* **Formulartitel anzeigen:** Möchtest du den Formulartitel nicht anzeigen lassen, kannst du es hier ausstellen.
* **Formularname:** Der Formularname ist wie ein Variablenname und wird nicht auf der Website angezeigt. Die Benennung folgt der Konvention: anmeldung-xxx-yyyy, wobei xxx für den Veranstaltungsnamen und yyyy für das Veranstaltungsjahr steht. Verwende bitte nur kleinbuchstaben und keine Sonderzeichen oder Umlaute! Im Falle von Veranstaltungen, für die Abkürzungen gebräuchlich sind (z.B. LV), kannst du auch gerne die Abkürzung verwenden. Beispiele für Formularnamen sind: anmeldung-grenzgaengerin-2022, anmeldung-lv-ii-2022.
* AJAX Überprüfung: Ja
* Scroll To Form On Error: Ja
* Erforderliche Felder werden markiert mit: \*
* Fehlermeldung: Bitte fülle alle verpflichtenden Felder aus!
* Remove Captcha for Logged Users: Nein
* Dankeschön-Nachricht anzeigen: Ja
* Show Thank You Message in Popup Window: Nein
* Scroll to Thank You Message: Ja
* Weiter-Button anzeigen: Ja
* Dankeschön-Nachricht:
  * Vielen Dank für deine Anmeldung!  
    Die Formulardaten wurden erfolgreich übermittelt.

    Du solltest in Kürze eine Bestätigungsmail an {registration_email:value} erhalten. Falls nicht, schau bitte in deinem Spam-Ordner nach und leere ggf. dein Postfach! In dieser E-Mail findest du einen Bestätigungslink. Sobald du diesen angeklickt hast, bist du angemeldet!

    Wenn du nach fünf Minuten noch keine E-Mail bekommen hast, wende dich bitte direkt an [oeffentlichkeitsarbeit@vcp-mitteldeutschland.de](mailto:oeffentlichkeitsarbeit@vcp-mitteldeutschland.de), damit wir nachschauen können, ob die Anmeldung bei uns eingegangen ist. Wenn nicht, wirst du uns nicht als angemeldet angezeigt und damit auch nicht eingeplant.
* **URL-Weiterleitung:** Wenn der\*die Benutzer\*in zu einer bestimmten Webpage weitergeleitet werden soll, nachdem er\*sie das Formular ausgefüllt hat, kannst du hier die Webpage-URL angeben.
* Daten in der Datenbank speichern: Ja
* Save IP to Database: Ja
* Delete Submissions older than (days): 0
* Bestätigung durch E-Mail aktivieren: Ja
* Redirect to URL after confirmation: Wenn der\*die Nutzer\*in nach der Bestätigung auf eine bestimmte Webpage weitergeleitet werden soll, kannst du hier die URL der Webpage angeben.
* Disable Submit Button on Subission: Nein
* Limit Submissions: Wenn es ein Limit an Teilnehmer\*innen geben sollen, kann das hier festgelegt werden (Achtung! Keine automatische Warteliste!).
* Mehrfachauswahl Trennzeichen: \\n (Das ist das Trennzeichen [neue Zeile] für die Mehrfachauswahl-Einträge, bspw. bei Dropdown, Checkbox-Gruppen etc.
* In Textbereichen für neue Zeilen <br /> verwenden: Ja

#### Formular Attribute

Hier sollte nichts verändert werden.

* Aktion
* Name
* Zusätzliche HTML-Attribute
* CSS ID: userForm
* CSS Klasse: anmeldung

#### Meta Tags

Hier sollte nichts verändert werden.

* Meta Beschreibung
* Meta Stichwort
* Formulartitel als Seitentitel verwenden: Nein

#### E-Mail an Benutzer

Die Einstellungen hier müssen sehr genau geprüft werden, ob sie korrekt sind. Die Optionen, wo du ggf. etwas verändern solltest, sind **fett** markiert.

* Sender (nicht verändern!)
  * Von: {global:mailfrom}
  * Vollst. Name: {global:fromname}
* Recipient
  * An: {registration_email:value} -> schickt die E-Mail an die von dem\*der Benutzer\*in angegebene E-Mail-Adresse
  * **Antwortadresse:** [landesbuero@vcp-mitteldeutschland.de](mailto:landesbuero@vcp-mitteldeutschland.de) -> Das ist die Adresse, an die der\*die Benutzer\*in antworten kann. Hier ist es in der Regel sinnvoll, deine Mitteldeutschland-Adresse einzutragen.
  * **Reply to Name**: Landesbüro VCP Mitteldeutschland -> Wenn du die Antwortadresse änderst, solltest du auch den angezeigten Namen entsprechend ändern
  * **CC (Kopie):** Hier könntest du z.B. Mitorganisator\*innen reinsetzen, damit an sie ebenfalls geantwortet wird.
  * **BCC (Blindkopie)**: Wenn ein Antwortadressat nicht ersichtlich sein soll, kann er\*sie hier eingetragen werden.
* Contents:
  * Betreff: Anmeldebestätigung für die Veranstaltung "{global:sitename}" des VCP Mitteldeutschland
  * **Inhalt der Mail:**
    * In den Inhalt könntest du ggf. erste Informationen zur Veranstaltung übermitteln.
    * [Bild der formatierten Mail einfügen]
  * Formatwahl: HTML
  * Auto-Generate Email Message: Nein
* Attachments
  * **Dateianhang:** Wenn du gleich mit der Bestätigungs-E-Mail eine Datei mitschicken möchtest, kannst du diesen hier einfügen. Bitte beachte den richtigen Speicherort (vergleiche Ordnerstruktur der Website)

#### E-Mail an Admin

Hier kannst du einstellen, ob du über eingehende Formulareinträge auch benachrichtigt werden möchtest. Vom Prinzip her gilt das gleiche wie bei E-Mail an Benutzer.

* Sender (nicht verändern!)
  * Von: {global:mailfrom}
  * Vollst. Name: {global:fromname}
* Recipient
  * An:
  * Antwortadresse: (Hier könnte bspw. die E-Mail Adresse des Benutzers\*der Benutzerin eingetragen werden, dann könntst du gleich an ihn\*sie antworten) Das Prinzip dazu wird unten erklärt.
  * Reply to name:
  * CC (Kopie):
  * BCC (Blindkopie):
* Contents
  * Betreff: Neue Veranstaltungsanmeldung
  * Inhalt der Mail: Liebe Veranstaltungsleitung, soeben gab es eine neue Anmeldung zu deiner Veranstaltung {global:formtitle}!
  * Formatwahl: HTML
  * Auto-Generate Email Message: Nein

#### Weitere E-Mail Adressen

Wird nicht von uns genutzt.

#### Deletion Email

Hier findest du die E-Mail-Einstellungen für die Abmeldung der Veranstaltung. Vom Prinzip sind sie genauso aufgebaut wie auch die anderen E-Mail-Einstellungen.

* Sender (nicht verändern!)
  * Von: {global:mailfrom}
  * Vollst. Name: {global:fromname}
* Recipient
  * An:
  * Antwortadresse: (siehe E-Mail an Admin)
  * Reply to name:
  * CC (Kopie):
  * BCC (Blindkopie):
* Contents
  * Betreff: Abmeldung von Veranstaltung "{global:formtitle}"
  * Inhalt der Mail:
  * Formatwahl: HTML

#### </>PHP-Skripte

PHP-Skripte sollten nur genutzt werden, wenn du dich damit auskennst.

* Skript, das bei Formularanzeige aufgerufen wird
* Skripte, die während der Formularverarbeitung aufgerufen werden
* Skripte, die nach der Formularverarbeitung aufgerufen werden

#### </>PHP Scripts - Pre-Processing

PHP-Skripte sollten nur genutzt werden, wenn du dich damit auskennst.

* Script called before form is generated
* Script called before form is validated

#### PHP E-Mail Skripte

PHP-Skripte sollten nur genutzt werden, wenn du dich damit auskennst.

* Das Script wird aufgerufen, bevor die E-Mail an den Benutzer gesendet wird.
* Script wird aufgerufen, bevor die E-Mail an den Benutzer gesendet wird.
* Das Script wird aufgerufen, bevor die übrigen E-Mails gesendet werden.

#### Mapping

Hier sollte nichts verändert werden.

#### Bedingte Felder

Bedingte Felder kannst du nutzen, um bestimmte Formularabfragen nur dann durchführen zu lassen, wenn eine bestimmte Bedingung eintritt.

Wir verwenden es zum Beispiel, um den konkreten Stamm abzufragen, wenn im Formular ausgewählt wird, dass die ausfüllende Person Mitglied im VCP Mitteldeutschland ist.  
Mit anderen Worten: Wenn die Person angibt, Mitglied im VCP MDE zu sein, muss sie anschließend auswählen, in welchem Stamm sie Mitglied ist. Wenn die Person nicht Mitglied im VCP MDE ist, geht es anders weiter. [Grafik zur vereinfachten Erklärung einfügen].

#### Weiterleitung (Silent Post)

Hier sollte nichts verändert werden.

* Sollen die Informationen an einen anderen Ort weitergeleitet werden? Nein
* Sollen die Informationen lautlos weitergeleitet weren: Ja
* Methode (normalerweise POST): POST
* Senden an URL:

#### Kalkulation

Mithilfe von Kalkulationen können Rechenoperationen durchgeführt werden, um beispielsweise das Alter bei Veranstaltungsbeginn auszurechnen.

### Aufrufen/Nutzen von eingetragenen Werten/Variablen

Die Code-Schnipsel, um (eingetragene) Werte abzurufen, haben folgende Struktur:

```
{variablenname:position_in_der_Variable}
```

Den Variablennamen findest du in den jeweiligen Feld-Einstellungen, also beispielsweise name.  
Die Position in der Variable ist in der Regel der Eingabewert: value.  
Um also beispielsweise den Namen abzurufen und damit weiterzuarbeiten nutzt du den Code-Schnipsel {name:value}.  
Fängt der Code-Schnipsel mit global an, dann handelt es sich um Einstellungen, die die gesamte Website betreffen. Diese kannst du nicht beeinflussen. Wenn du Fragen dazu hast, um globale Variablen zu nutzen, wende dich an den AK Öffentlichkeitsarbeit ([oeffentlichkeitsarbeit@vcp-mitteldeutschland.de](mailto:oeffentlichkeitsarbeit@vcp-mitteldeutschland.de)).

### Dokumentation der eigenen Erweiterungen

#### Alter bei Veranstaltungsbeginn

> Dier Abschnitt dient nur Dokumentationszwecken. Um einen Veranstaltungstermin mit Anmeldung zu erstellen, ist er für dich normalerweise nicht relevant.

Um das Alter bei Veranstaltungsbeginn zu berechnen und bei der Anmeldung auch mit auszugeben, wurde in der großen Vorlage die folgende Lösung implementiert:

* Zusätzliches verstecktes Feld mit Variablenname "AlterBeiVeranstaltungsbeginn" wird im Formular hinzugefügt.
* Unter Eigenschaften>CSS und Javascript wird in RSForms! ein Codesnippet eingefügt, was
  * den Starttermin der Veranstaltung ausliest (basiert auf dem von sketchdates generierten HTML-Gerüst)
  * den Geburtstag der sich anmeldenden Person ausliest
  * das Alter bei Veranstaltungsbeginn berechnet

Der dafür genutzte Code ist der folgende:

```
<script type="text/javascript">
function calculateAge(){
    // Veranstaltungsbeginn abfragen
    let textEntry = document.getElementsByClassName('sketchdates-datetime')[0].nextElementSibling.innerHTML;
    let startDate = new Date(textEntry.substr(6,4), textEntry.substr(3,2) - 1, textEntry.substr(0,2));
    // Geburtstag abfragen
    let year = parseInt(document.getElementById('Geburtstagy').value,10);
	  let month = parseInt(document.getElementById('Geburtstagm').value,10)-1;
    let day = parseInt(document.getElementById('Geburtstagd').value,10);
    let age = startDate.getFullYear() - year;
    // Alter berechnen
    if (month > startDate.getMonth()) {
        age = age - 1;
    };
    if (month === startDate.getMonth()) {
        if (day > startDate.getDate()) {
            age = age - 1;
        }
    };
    // Ergebnis ausgeben
    if (!isNaN(age)) {
document.getElementById('AlterBeiVeranstaltungsbeginnAnzeige').innerText= "Alter bei Veranstaltungsbeginn: " +(age); 
    document.getElementById('AlterBeiVeranstaltungsbeginn').value= age.toString(); 
    };
}
</script>
```

#### Anmeldeschluss

Nach Anmeldeschluss soll das Anmeldeformular nicht mehr angezeigt werden. Dies wird gelöst, indem am Formularende ein verstecktes Feld eingefügt wird, in das die Deadline eingegeben wird (Format: DD/MM/YYYY/ HH/MM/SS). Wenn das Formular geladen wird, wird die folgende Funktion aktiviert und löscht alle Felder. Stattdessen wird die Nachricht "Die Anmeldefrist ist bereits abgelaufen." angezeigt:

```
window.onload = function(){
    let deadline = document.getElementById('deadline').value;
    let deadlineDate = new Date(deadline.substr(6,4), deadline.substr(3,2)-1 , deadline.substr(0,2), deadline.substr(11,2), deadline.substr(14,2), deadline.substr(17,2));
    let today = new Date(); 
    if (today > deadlineDate){
        document.getElementById('userForm').innerHTML = "<p>Die Anmeldefrist ist bereits abgelaufen.</p>";
    }
}; 
```
