# Matomo und Metadaten 

## Matomo 

### Was ist Matomo?

Matomo ist ein Webanalysetool, welches die datenschutzkonforme Auswertung von Nutzer*innendaten erlaubt. So werden keine z.B. keine Cookies gesetzt.

### Wozu wir Matomo nutzen

Wir nutzen Matomo, *Überraschung*, zur Analyse der Besuchenden unserer Website;) Im Speziellen geht es uns darum, zu verstehen, welche Inhalte gut angenommen werden.
Das erlaubt uns, 

1. zu erkennen, welche Inhalte wir häufiger aktualisieren müssen.
2. unsere Öffentlichkeitsarbeit so auszurichten, dass wir mehr Menschen erreichen. 

### Accounts

Grundsätzlich können alle Mitglieder aus dem AK Öffentlichkeitsarbeit sowie der Landesleitung und des Landesbüros Zugänge zu Matomo erhalten.

Der Username hat die Form `vorname.nachname`. 
Bei Registrierung wird eine E-Mail-Adresse benötigt - dafür wird immer die mitteldeutsche E-Mail-Adresse verwendet (`vorname.nachname@vcp-mitteldeutschland.de`).
Das Passwort muss nach dem ersten Log-in geändert werden. Die Passwort-Sicherheit wird durch Matomo vorgegeben. 
Falls gewünscht, kann auch eine Zwei-Faktor-Authentifizierung eingerichtet werden (nur zu empfehlen!).

Den Admin-Zugang zu Matomo verwaltet die Beauftragung für interne Kommunikation und Öffentlichkeitsarbeit.

## Suchmaschinenoptimierung (SEO)

Damit Beiträge auch bei Suchmaschinenergebnissen (z.B. über DuckDuckGo, Google, Ecosia, Bing, MetaGer, …) angezeigt werden, kann SEO betrieben werden. 
Dafür ist ein griffiger, eindeutiger Titel wichtig, aber eben noch viel mehr: zum Beispiel, und das ist für unsere Zwecke wichtig, die Meta-Beschreibung. 
Zu ihr schreibt Google folgendes: 

> #### Meta-Beschreibungs-Tag verwenden
>
> Im Meta-Beschreibungs-Tag sind die auf der betreffenden Seite behandelten Themen für Google und andere Suchmaschinen zusammengefasst. Der Titel einer 
> Seite kann mehrere Wörter oder einen Ausdruck umfassen. Das Meta-Beschreibungs-Tag einer Seite hingegen kann ein oder zwei Sätze oder sogar einen kurzen 
> Absatz enthalten. Wie das `<title>`-Element wird auch das Meta-Beschreibungs-Tag im `<head>`-Element des HTML-Dokuments platziert.
> 
> #### Was sind die Vorzüge von Meta-Beschreibungs-Tags?
> 
> Meta-Beschreibungs-Tags spielen eine wichtige Rolle, weil Google sie möglicherweise als Snippets für deine Seiten in den Google-Suchergebnissen verwendet. 
> Beachte, dass wir „möglicherweise“ sagen, weil Google eventuell auch einen relevanten Abschnitt des sichtbaren Textes deiner Seite verwendet, wenn er gut 
> zur Suchanfrage eines Nutzers passt. Es empfiehlt sich immer, den einzelnen Seiten Meta-Beschreibungs-Tags hinzuzufügen – für den Fall, dass Google keine 
> gute Textauswahl zur Verwendung im Snippet finden kann. [Weitere Informationen zum Erstellen hochwertiger Meta-Beschreibungen](https://developers.google.com/search/docs/advanced/appearance/snippet?hl=de#meta-descriptions)
> 
> #### Seiteninhalte korrekt zusammenfassen 
> 
> Verfasse eine Beschreibung, die für Nutzer informativ und interessant ist, wenn diese dein Meta-Beschreibungs-Tag als Snippet in einem Suchergebnis sehen. 
> Für die Textlänge in einem description-Meta-Tag gibt es keine Mindestvorgabe oder Obergrenze. Wir empfehlen jedoch eine ausreichende Länge, bei der der Text 
> vollständig in der Suche angezeigt wird und alle relevanten Informationen enthält, die Nutzer für die Einschätzung benötigen, ob die Seite nützlich und relevant 
> für sie ist. Beachte aber, dass Nutzern je nach Suchform und -ort eventuell unterschiedlich große Snippets angezeigt werden. Vermeide dabei:
> 
> * Meta-Beschreibungs-Tags mit Inhalten, die keinen Bezug zu den Inhalten auf der Seite haben.
> * allgemeine Beschreibungen wie „Dies ist eine Webseite“ oder „Seite über Baseballkarten“
> * Beschreibungen, die ausschließlich aus Keywords bestehen
> * das Kopieren des gesamten Dokumentinhalts in das Meta-Beschreibungs-Tag
> 
> #### Für jede Seite eindeutige Beschreibungen verwenden
> 
> Wenn du für jede Seite ein anderes Meta-Beschreibungs-Tag festlegst, hilft dies sowohl Nutzern als auch Google – insbesondere bei Suchanfragen, bei denen Nutzer 
> mehrere Seiten in deiner Domain aufrufen können, z. B. bei Suchen mit dem Operator site:. Doch falls deine Website Tausende oder sogar Millionen von Seiten hat, 
> ist es wahrscheinlich nicht möglich, für alle Seiten manuell Meta-Beschreibungs-Tags zu erstellen. In diesem Fall kannst du Meta-Beschreibungs-Tags basierend auf 
> dem Inhalt der einzelnen Seiten automatisch generieren.
> Vermeide dabei die Verwendung desselben Meta-Beschreibungs-Tags für alle Seiten deiner Website oder für eine große Gruppe von Seiten

Eine weitere, deutlich ausführlichere Einschätzung bietet beispielsweise der [Blog SEBO Content](https://sebo-content.de/meta-beschreibung/). 

Welche Schlussfolgerungen wir aus diesen Informationen für unsere Beitragserstellung haben, findest du in Abschnitt 2 [Suchmaschinenoptimierung (SEO) in Beiträgen](#seo-content). 